### ISSUE TITLE
quickedit fails to edit script with formatting symbols!

### ISSUE THREAD

**Issue by Lampe2020** [Stehlampe2020/lampe2020-linux-utils#1]
When I try to quickedit a script with e.g. a date request, it fails, says the file is back to original but really isn't. Luckily I had a copy of the script to restore the original!

**Comment by Lampe2020** [comment]
I have a workaround, though it's a bit tedious for scripts with more symbols printf cannot understand or tries to interprete: just escape every symbol that makes issues with a "\\"
(I will update quickedit to save the original file as a copy on the filesystem instead of in a variable. I will probably completely re-write the whole thing in Python3 if I cannot fix this.)
Maybe

**Comment by Stehlampe2020** [comment]
Works now.

**Comment by Lampe2020** [comment]
Works now.
